### ISSUE TITLE
Working on TPM2 Support

### ISSUE THREAD

**Issue by DestroyerXyz** [Foxboron/sbctl#108]
Hi @Foxboron,

I am thinking about starting work on TPM support (2.0 only in the beginning) for the project. Are you already working on it? If not can you give me some tips? I have read some documentation and get the gist of it.

Thanks

**Comment by Foxboron** [comment]
Yo, thanks for looking at it :)

I have a POC with `go-uefi` that implements some very basic standalone TPM support.

https://github.com/Foxboron/go-uefi/blob/morten/tpm/cmd/gotpm/main.go

The issues for implementing this is:
* Add some state that says which key type sbctl is using. This could be a file in the Keydir.
* Abstract the key operations in `sbctl`.

My POC uses `go-tpm-tools` since we need a TPM abstraction which implements the `crypto.Signer` interface. However this means we do not get sealing towards PCRs. I started hacking a bit on `go-tpm-tools` to get PCR sealing supported but it's a bit of work I haven't had time to fix yet.

Feel free to write something up and send a draft. We can work out any issues as you go along :)

**Comment by DestroyerXyz** [comment]
What about using these:
https://archlinux.org/packages/community/x86_64/tpm2-tss/

**Comment by Foxboron** [comment]
I would prefer if we didn't shell out to external dependencies when Go has the amount of native code for the TPM2 stack that it has.

I don't really want to add C dependencies since it is quite nice that we could statically compile `sbctl`.

**Comment by DestroyerXyz** [comment]
Ok, I understand that
Reading the go-tpm documentation now
