### ISSUE TITLE
Nvidia problem

### ISSUE THREAD

**Issue by jyash8** [Foxboron/sbctl#221]
I have seen many places, pc with nvidia drivers fail to boot.
Do something different needs needs to done for it or will it out of the box?
Also how to disable checks for kernel modules.

**Comment by critkitten** [comment]
As far as I understand sbctl does not support signing of kernel modules.
If you want to know more checkout https://github.com/Foxboron/sbctl/issues/85

To disable signature check of kernel module you can set the following kernel cmdline:
`module.sig_enforce=0`
But Secureboot usually means that `lockdown=confidentiality` is on which in turn means module signature also.

Under archlinux I have not been able to run secureboot with an Nvidia card. Under Debian it works because only mok is used there. 
The difference between mok and sbctl you can read in the above linked article. I did not understand it until today. 

Perhaps someone can clarify this in a short sentence.

**Comment by jyash8** [comment]
As far as I know nvidia kernel module has been open sourced so if the kernel module could be embedded in kernel and then made unified kernel image and signed would it then work

**Comment by IPlayZed** [comment]
> Under archlinux I have not been able to run secureboot with an Nvidia card. Under Debian it works because only mok is used there and the kernel are official signed archlinux not.

This is interesting, I had no such problem. I think the kernel is not built with lockdown enabled, so unless you specify `lockdown=confidentiality` and add `lockdown` to `lsm=...`, there is no reason why it should force itself. When I had an Nvidia card, I could do it easily.

`lockdown` forces `module.sig_enforce=0` AFAIK.

> The difference between mok and sbctl you can read in the above linked article. I did not understand it until today. But you can´t use both.

Why not? Sign the shim, boot the shim, which launches the MOK process of validating stuff.
[This](https://tianocore-docs.github.io/Understanding_UEFI_Secure_Boot_Chain/draft/additional_secure_boot_chain_implementations/machine_owner_key_mok.html) page explaining it simply.

**Comment by IPlayZed** [comment]
> As far as I know nvidia kernel module has been open sourced so if the kernel module could be embedded in kernel and then made unified kernel image and signed would it then work

That is not really the case, again the question if it signed by the same key as the one used to sign the kernel. If you build your own kernel, sign the kernel module with that, it will not be rejected.

**Comment by IPlayZed** [comment]
> > As far as I know nvidia kernel module has been open sourced so if the kernel module could be embedded in kernel and then made unified kernel image and signed would it then work
> 
> That is not really the case, again the question if it signed by the same key as the one used to sign the kernel. If you build your own kernel, sign the kernel module with that, it will not be rejected.

It looks like Nvidia will add upstream support for the official kernel modules, so in the future you will be able to use it without any hassle, if you have the right hardware.
