### ISSUE TITLE
Make a 1.0 release without go-uefi?

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/sbctl#42]
My original plan was to hack on go-uefi and ensure we could port all the functionality from `sbsigntools`. But I'm'slow and we are soon at 1 year since the release of both tools.

I'm wondering if we should much rather try get the basic configuration stuff into `sbctl` and do a 1.0 release.

**Comment by ericonr** [comment]
As a packager, I would appreciate a release, since it allows me to unleash `sbctl` on the people :)

That said, I would suggest a 0.x release first, which would allow us to fix UX issues that appear when hopefully more people are testing the software, since there isn't a promise of a stable interface.

**Comment by Foxboron** [comment]
Ah yes. Good idea. I should probably just cut a 0.1 release tomorrow and be less conservative about this!
