### ISSUE TITLE
Follow recommended project layout

### ISSUE THREAD

**Issue by ericonr** [Foxboron/sbctl#8]
According to https://github.com/golang-standards/project-layout, commands should go in `cmd/<command-name>/`, and all supporting files in either `pkg/` or `internal/`, depending on if you wish to export them to other Go projects. That would allow the `sbctl` command to be installed with `go install ./...`, which is considerably easier.

I would be interested in making these changes if you agree to them, just need to know where you'd prefer the supporting files to be (pkg or internal).

**Comment by Foxboron** [comment]
Looking quickly over the "golang-standards" project it's just subjective stuff. The `pkg/` vs `internal/` are misnormers as anything inside `pkg/` fit for other projects should be separate projects. `cmd/main.go` is mainly done because there there is just one command, and `go install ./...` is frankly not how you should install anything , so not sure if I'd like to cater for it....

**Comment by ericonr** [comment]
Fair enough. I like `go install ./...` because it allows one to get all the binaries from a repo easily, if there are ever new binaries for this project (doesn't seem likely, though).

Having at least `cmd/sbctl/main.go` does allow one to build the command without needing to specify any output, like so: `go build ./cmd/sbctl` and `go install ./cmd/sbctl`. If you feel that isn't useful, I can close the issue.

**Comment by Foxboron** [comment]
Moving to `cmd/sbctl/main.go` is fine frankly. But I don't feel like sorting stuff into `pkg/` nor `internal/`

**Comment by ericonr** [comment]
Yeah, fair enough. I will do that, then. Thanks!

**Comment by Foxboron** [comment]
Nonono. Thank you!
