### ISSUE TITLE
add the `--sign` option to the `bundle` command

### ISSUE THREAD

**Issue by beroal** [Foxboron/sbctl#89]
Since the `bundle` command writes the bundle to the file system, why not allow a user to sign the bundle in the same command?

**Comment by conrad-heimbold** [comment]
I guess it's because of the good-old [UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy): 

**1. Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".** 
That's why `bundle` only does the bundling, but not the signing. 


**2. Expect the output of every program to become the input to another, as yet unknown, program.**
The output of the `bundle` command can be used as the input of the `sign` command.

**Comment by beroal** [comment]
@conrad-heimbold all these commands are executed by one program `sbctl`.

**Comment by Foxboron** [comment]
Not doing new features to the UKI stuff.
